with-expecter: true

resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/COS301-SE-2025/Swift-Signals/api-gateway/internal/client:
    config:
      dir: "internal/mocks/client"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      UserClientInterface:
      IntersectionClientInterface:
      OptimisationClientInterface:

  github.com/COS301-SE-2025/Swift-Signals/api-gateway/internal/service:
    config:
      dir: "internal/mocks/service"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      AuthServiceInterface:
      IntersectionServiceInterface:

  github.com/COS301-SE-2025/Swift-Signals/protos/gen/intersection:
    config:
      dir: "internal/mocks/grpc_client"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      IntersectionServiceClient:
      IntersectionService_GetAllIntersectionsClient:

  github.com/COS301-SE-2025/Swift-Signals/protos/gen/optimisation:
    config:
      dir: "internal/mocks/grpc_client"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      OptimisationServiceClient:

  github.com/COS301-SE-2025/Swift-Signals/protos/gen/user:
    config:
      dir: "internal/mocks/grpc_client"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      UserServiceClient:
      UserService_GetUserIntersectionIDsClient:
