services:
  user-service:
    build:
      context: ../user-service
      dockerfile: ../build/package/Dockerfile.user
    image: swift-signals/user-service:dev
    container_name: user-service
    environment:
      DB_HOST: user-postgres
      DB_PORT: 5432
      DB_USER: user_service
      DB_PASSWORD: password
      DB_NAME: user_service_db
      APP_PORT: 50051
    depends_on:
      - user-postgres
    ports:
      - "50051:50051"
    networks:
      - app-network

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    volumes:
      - user_pgdata:/var/lib/postgresql/data
      - ../user-service/internal/db/postgres_schema.sql:/docker-entrypoint-initdb.d/postgres_schema.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-network


  intersection-service:
    build:
      context: ../intersection-service
      dockerfile: ../build/package/Dockerfile.intersection
    image: swift-signals/intersection-service:dev
    container_name: intersection-service
    environment:
      APP_PORT: 50052
      MONGO_URI: mongodb://intersection-mongo:27017
    depends_on:
      - intersection-mongo
    ports:
      - "50052:50052"
    networks:
      - app-network

  intersection-mongo:
    image: mongo:6.0
    container_name: intersection-mongo
    environment:
      MONGO_INITDB_DATABASE: IntersectionService
    volumes:
      - intersection_mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network


  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: ../build/package/Dockerfile.api-gateway
    image: swift-signals/api-gateway:dev
    container_name: api-gateway
    depends_on:
      - user-service
      - intersection-service
    environment:
      APP_PORT: 9090
      USER_GRPC_ADDR: user-service:50051
      INTR_GRPC_ADDR: intersection-service:50052
    ports:
      - "9090:9090"
    networks:
      - app-network

  chatbot-server:
    build:
      context: ../frontend/chatbot_server
      dockerfile: ../../build/package/Dockerfile.chatbot
    image: swift-signals/chatbot-server:dev
    container_name: chatbot-server
    environment:
      DIALOGFLOW_PROJECT_ID: swift-signals
      DIALOGFLOW_CLIENT_EMAIL: swift-signals-api-user@swift-signals.iam.gserviceaccount.com
      DIALOGFLOW_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDftvNdAhIudos+\n71DDbn/fBGZcsotq3UihiVuknhm+40Ci5i0dQTX7O2W/14cIfLDlte8P7sR0Lg5/\nu8pGO1g2Ri3i6ZdQoAI5At4K2/Xpt0P3wPnSmJ/2Lhpo98U/mJ7Ec3smZkyzDkeL\nzMMM7EAFSipv+uuBWmUQZDAhK+xkb0EXZ0BOd0bc13rMBkT+jhB9XWFdHRebm0ZF\ngCTp6K60cQWtgojk2aI5mAAkXN/I3yru9sBoUwICefdDB2szf9QQ//Hx7KgSJUxu\nQPDeJc2PlkrWkwvzTp4GLkicrvMgJXU2kiijwDh0snAnGldBAZGf4udAyVGRx0md\n156j1Sc3AgMBAAECggEAC9gwtV1tNKw5E3Qckg770oUgnaAkX9w8bV+2NuvZ+sXR\nv8OGYvSiFN2gYFJbHLjBWEAphUND1STfxqUyK0VsFl+L1ruTCS/s6N4n1GpbRZcF\nkGIADXA1k+qn96PFUT3Vi3ApIS+BuGnf9t0N/Kqrebw4rU9wgEZBcJHlYcmPYq0k\njjHgfd1AUzaRPb22n+CYVfpda2Cv3G3R/kqglKhlPm5GHH+b0QdIOE9tmlrjpYJa\nfo5qPyAlbeQKOaK30bK/u3ZO2cEL3AShSVM9+8S9noTCA7FTtdjs1nsMY1Vh+8MW\nCB7Ac26c54tS2w4KMGmi7ZUciqv8zGtzdWd2HsvBAQKBgQD8zPLX+h5qSwGO8NLI\nRjvYQ8OMWnOdrB6lg+9sL/WnZsceeh7ub2DjqFA++ON0TYTkorPvTBcEejt8qNaY\njuvynkmiqGFzbz7z40Gr4WII/CvQww3w/ioYsZRyKhv7i2ZSBD4fZcQ/o/Sp+emd\ndGymJo5hk2xP+SIXQX2sa1CCNwKBgQDii8QmC8rZHfMOFEKSk5Aqb26qsVNMIopn\n3UwXmNx/Ekhjm8g23z0QS5XX7yxL3ONeGSOWCPxp4skAlXka0SW1oe11+srklOUY\nAIyYMlxZww+9JRD/On86/jbirc+NkAUIkmRS3BmISoumGqFhV4hEJvQI9Ti/BI2M\nHGpoyfIDAQKBgBNQWTFVA6PdTSYtkf0JGKNiMft0IacnMkQ0+0LJuzvp50aVz+0p\nhz59anwVKdOF5KRPJe4fYxbNe+P/Rj3rlW042Klbse5OzoF1mFvYYVQMaBCQBm2m\nDXNLhere+rpSISQc/N4LOV4fWZ7u4AFOlspu4avkxn6pqwgZ0c8td74rAoGBAJcg\nU8ZpoXU7NHQU8eAkDk0wruuxhXbJp/jnuKYZNCaUxLOmLWblfy/KrHgzNiKZhRe1\nv3aMIg5k2l/IVtSb5wMGtYk5t3XLGhTr8N5q4g6DQJGWE4Ofu1ZYVbbb6hRumd0B\nA2n/KA0yZXx2UWfFY8LLFYqQQ72xxNdN8XJcHVUBAoGBANx1o4IAtU3zhbruqEj2\nXpekUw+7gmXemJ5Zl9wj0f/4rm1SBqSnFGPlXOoBjCKFxvVCvKMbOcu9Bqage37q\naWbCSjJkrHkxFiKSBDEQ+nj2POcgaiYG8QV6JS5ANj6dLIm4RCHHQRDiIQrWw9nS\nqrLqYxUCSUrKd0+0MrH/Q+Kr\n-----END PRIVATE KEY-----\n"
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../build/package/Dockerfile.frontend
    image: swift-signals/frontend:dev
    container_name: frontend
    depends_on:
      - chatbot-server
      - api-gateway
    ports:
      - "80:80"
    networks:
      - app-network

  # metric-postgres:
  #    image: postgres:16
  #    container_name: metric-postgres
  #    environment:
  #      POSTGRES_USER: metric_service
  #      POSTGRES_PASSWORD: password
  #      POSTGRES_DB: metric_service_db
  #    volumes:
  #      - metric_pgdata:/var/lib/postgresql/data
  #    ports:
  #      - "5433:5432"
      


volumes:
  user_pgdata:
  intersection_mongodata:
  # metric_pgdata:

networks:
  app-network:
    driver: bridge
