FROM golang:1.25.1-alpine

RUN apk add --no-cache \
    protobuf \
    protobuf-dev \
    make \
    git \
    curl \
    unzip

WORKDIR /app
COPY protos/ protos/
COPY shared/ shared/
COPY api-gateway/ api-gateway/

WORKDIR /app/protos/swiftsignals/
RUN make api-gateway

WORKDIR /app/api-gateway/
RUN make dockerfile
CMD ["./bin/api-gateway"]
