FROM python:3

WORKDIR /app

RUN apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/* 

COPY optimization-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY protos/ protos/

WORKDIR /app/protos/swiftsignals/
RUN make clean-gen
RUN make generate-py 

ENV PYTHONPATH="/app/gen/python:$PYTHONPATH"

COPY optimization-service/ .

CMD ["python", "server/server.py"]
