FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/chatbot_server/package*.json ./
RUN npm ci
COPY frontend/chatbot_server/ .

FROM gcr.io/distroless/nodejs18-debian11:nonroot
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/index.js ./
ENTRYPOINT ["node", "index.js"]
