version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - exhaustive
    - loggercheck
    # - testifylint
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
    # - swaggo
run:
  timeout: 5m
  relative-path-mode: gomod
