FROM node:18-alpine AS build
WORKDIR /app

ARG VITE_API_BASE_URL=localhost:9090
ARG VITE_CHATBOT_BASE_URL=localhost:3001/chatbot

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_CHATBOT_BASE_URL=$VITE_CHATBOT_BASE_URL

COPY frontend/package*.json ./
RUN npm ci 
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]


