apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: swift-signals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: myregistry/swift-signals/api-gateway:latest
        ports:
        - containerPort: 9090
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: GATEWAY_APP_PORT
        - name: USER_GRPC_ADDR
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: USER_GRPC_ADDR
        - name: INTR_GRPC_ADDR
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: INTR_GRPC_ADDR
        - name: SIMU_GRPC_ADDR
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: SIMU_GRPC_ADDR
        - name: OPTI_GRPC_ADDR
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: OPTI_GRPC_ADDR
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: swift-signals
spec:
  selector:
    app: api-gateway
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
