apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-server
  namespace: swift-signals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-server
  template:
    metadata:
      labels:
        app: chatbot-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: chatbot-server
        image: insideinsights/repo:chatbot-1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DIALOGFLOW_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DIALOGFLOW_PROJECT_ID
        - name: DIALOGFLOW_CLIENT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DIALOGFLOW_CLIENT_EMAIL
        - name: DIALOGFLOW_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: swift-signals-secrets
              key: DIALOGFLOW_PRIVATE_KEY
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: CHATBOT_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-server
  namespace: swift-signals
spec:
  selector:
    app: chatbot-server
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP

