apiVersion: apps/v1
kind: Deployment
metadata:
  name: intersection-service
  namespace: swift-signals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intersection-service
  template:
    metadata:
      labels:
        app: intersection-service
    spec:
      containers:
      - name: intersection-service
        image: myregistry/swift-signals/intersection-service:latest
        ports:
        - containerPort: 50052
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: INTERSECTION_APP_PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: MONGO_URI
        readinessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: intersection-service
  namespace: swift-signals
spec:
  selector:
    app: intersection-service
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  type: ClusterIP
