apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: swift-signals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: myregistry/swift-signals/user-service:latest
        ports:
        - containerPort: 50051
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: swift-signals-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: DB_NAME
        - name: DEFAULT_USER_NAME
          valueFrom:
            secretKeyRef:
              name: swift-signals-secrets
              key: DEFAULT_USER_NAME
        - name: DEFAULT_USER_EMAIL
          valueFrom:
            secretKeyRef:
              name: swift-signals-secrets
              key: DEFAULT_USER_EMAIL
        - name: DEFAULT_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: swift-signals-secrets
              key: DEFAULT_USER_PASSWORD
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: swift-signals-config
              key: USER_APP_PORT
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: swift-signals
spec:
  selector:
    app: user-service
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP
