with-expecter: true
recursive: true

resolve-type-alias: false         
disable-version-string: true     
issue-845-fix: true             

packages:
  github.com/COS301-SE-2025/Swift-Signals/intersection-service/internal/db:
    config:
      dir: "internal/mocks/db"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      IntersectionRepository:

  github.com/COS301-SE-2025/Swift-Signals/intersection-service/internal/service:
    config:
      dir: "internal/mocks/service"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      IntersectionService:

  github.com/COS301-SE-2025/Swift-Signals/protos/gen/intersection:
    config:
      dir: "internal/mocks/grpc"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      IntersectionService_GetAllIntersectionsServer:

