FROM golang:1.24.5-alpine

WORKDIR /app
COPY protos/ protos/
COPY shared/ shared/
COPY api-gateway/ api-gateway/

WORKDIR api-gateway
RUN go mod tidy
RUN go mod download

WORKDIR cmd
RUN go build -o main 
CMD ["./main"]
