FROM golang:1.24.5-alpine

WORKDIR /app
COPY protos/ protos/
COPY shared/ shared/
COPY user-service/ user-service/

WORKDIR user-service
RUN go mod tidy
RUN go mod download

WORKDIR cmd
RUN go build -o main 
CMD ["./main"]
