with-expecter: true

resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/COS301-SE-2025/Swift-Signals/user-service/internal/db:
    config:
      dir: "internal/mocks/db"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      UserRepository:

  github.com/COS301-SE-2025/Swift-Signals/user-service/internal/service:
    config:
      dir: "internal/mocks/service"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      UserService:

  github.com/COS301-SE-2025/Swift-Signals/protos/gen/user:
    config:
      dir: "internal/mocks/grpc"
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      UserService_GetAllUsersServer:
      UserService_GetUserIntersectionIDsServer:
