name: API Unit Tests

on:
  push:
    branches: [api-gateway]
  pull_request:
    branches: [api-gateway]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'  

      - name: Generate Proto Files
        working-directory: ./protos
        run: |
          make install-protoc
          make generate

      - name: Generate Mockery Files
        working-directory: ./api-gateway
        run: |
          go install github.com/vektra/mockery/v2@latest
          mockery

      - name: Run unit tests in api-gateway
        working-directory: ./api-gateway  
        run: |
          go mod tidy
          go test -v ./... 
