name: API Linting

on:
  push:
    branches: [main, dev, api-gateway]
  pull_request:
    branches: [main, dev, api-gateway]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: '1.24.6'

        - name: Generate Proto Files
          working-directory: ./protos
          run: |
            make install-protoc
            make generate

        - name: Generate Mockery Files
          working-directory: ./api-gateway
          run: |
            go install github.com/vektra/mockery/v2@latest
        
            # Client mocks
            mockery --name=UserClientInterface --dir=./internal/client --output=./internal/mocks/client
            mockery --name=IntersectionClientInterface --dir=./internal/client --output=./internal/mocks/client
            mockery --name=OptimisationClientInterface --dir=./internal/client --output=./internal/mocks/client
        
            # Service mocks
            mockery --name=AdminServiceInterface --dir=./internal/service --output=./internal/mocks/service
            mockery --name=ProfileServiceInterface --dir=./internal/service --output=./internal/mocks/service
            mockery --name=AuthServiceInterface --dir=./internal/service --output=./internal/mocks/service
            mockery --name=IntersectionServiceInterface --dir=./internal/service --output=./internal/mocks/service
        
            go mod tidy

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            version: v2.1
            working-directory: ./api-gateway
