name: Intersection Service Linting

on:
  push:
    branches: [intersection-service]
  pull_request:
    branches: [intersection-service]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.24.0' 

        - name: Install tools
          run: |
            go install github.com/vektra/mockery/v2@v2.53.4
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
            go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
            curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v27.2/protoc-27.2-linux-x86_64.zip
            sudo unzip -o protoc-27.2-linux-x86_64.zip -d /usr/local

        - name: Generate Proto Files
          working-directory: ./protos
          run: |
            make install-protoc
            make generate

        - name: Generate Mocks
          working-directory: ./intersection-service
          run: make mocks

        - name: Run go mod tidy
          working-directory: ./intersection-service
          run: go mod tidy

        - name: Run golangci-lint
          working-directory: ./intersection-service
          run: make lint
