name: React Frontend

on:
  push:
    branches: [main, dev, frontend, feature/ChatBot]
  pull_request:
    branches: [main, dev, frontend, feature/ChatBot]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install ESLint
      run: npm install --save-dev eslint
      
    - name: Run ESLint
      run: npx eslint "**/*.{js,jsx,ts,tsx}" || echo "No files to lint"
    
    - name: Check Prettier formatting
      run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"

    - name: Run Jest tests
      run: npx jest --passWithNoTests
