name: Lint React TS App

on:
  push:
    branches: [Joshua-UI-Updates, UI-Linting-Fixes]
  pull_request:
    branches: [Joshua-UI-Updates, UI-Linting-Fixes]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 #adjust if we are running a different version

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx eslint . --ext .ts,.tsx --max-warnings=0
