name: Python Lint and Test

on: 
    push:
        branches: [main, dev, SumoSimulationWork]
    pull_request:
        branches: [main, dev, SumoSimulationWork]

jobs:
    check-python:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install sumolib traci
            pip install flake8 pytest
            pip install pytest-mock

        - name: Run Linting with Flake8
          run: |
            flake8 Sumo_Project_Breakdown --ignore=E501

        - name: Run Tests with Pytest
          run: |
            pytest Sumo_Project_Breakdown