name: Python Lint and Test

on: 
    push:
        branches: [main, dev, SumoSimulationWork]
    pull_request:
        branches: [main, dev, SumoSimulationWork]

jobs:
    check-python:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install sumolib traci
            pip install flake8 pytest
            pip install pytest-mock
            pip install pytest-cov

        - name: Install SUMO
          run: sudo apt-get update && sudo apt-get install -y sumo sumo-tools sumo-doc

        - name: Set SUMO_HOME
          run: echo "SUMO_HOME=/path/to/sumo/home" >> $GITHUB_ENV

        - name: Run Linting with Flake8
          run: |
            flake8 Sumo_Project_Breakdown --ignore=E501

        - name: Create results directory
          run: mkdir -p out/results

        - name: Run Tests with coverage using Pytest
          run: |
            pytest --cov=SimLoad --cov-report=term-missing Sumo_Project_Breakdown/tests/