name: User Service Linting

on:
  push:
    branches: [user-service]
  pull_request:
    branches: [user-service]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    - name: Install Protobuf Compiler
      run: | 
        sudo apt-get update && sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
        echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Generate Proto Files
      working-directory: ./protos
      run: |
        mkdir -p gen/user
        protoc --go_out=./gen/user/ --go_opt=paths=source_relative --go-grpc_out=./gen/user/ --go-grpc_opt=paths=source_relative user.proto 
        cd gen
        go mod init github.com/COS301-SE-2025/Swift-Signals/protos/gen

    - name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: stable
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            version: v2.1
            working-directory: ./user-service
