name: User Service Unit Tests

on:
  push:
    branches: [user-service]
  pull_request:
    branches: [user-service]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'  

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Generate Proto Files
        working-directory: ./protos
        run: |
          protoc --go_out=./gen/user/ --go_opt=paths=source_relative --go-grpc_out=./gen/user/ --go-grpc_opt=paths=source_relative user.proto 

      - name: Generate Mockery Files
        working-directory: ./user-service
        run: |
          go install github.com/vektra/mockery/v2@latest
          mockery

      - name: Run unit tests in user-service
        working-directory: ./user-service  
        run: |
          go mod tidy
          go test -v ./.. 
