name: User Service Linting

on:
  push:
    branches: [user-service]
  pull_request:
    branches: [user-service]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.24.x'
            cache: true

        - name: Check Go version
          run: go version

        - name: Generate Proto Files
          working-directory: ./user-service
          run: make proto
        
        - name: Run golangci-lint
          working-directory: ./user-service
          run: make lint
